version: 2
updates:
  # 1. 监控 Gradle 依赖与 libs.versions.toml
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v3"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10

  # 2. 监控 GitHub Actions Workflow 动作版本
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "v3"
    commit-message:
      prefix: "ci(deps)"
    open-pull-requests-limit: 5
