ver: "1.0"

bot: 
    address: "localhost:8080"
    token: ""
admins: 
    - 10000
groups: 
    - 10000

feature: 
    cmdPrefix: "/"
    load: 
        enable: true
        pic: false
    message: 
        enable: true
        mode: 0
        prefix: "#"
        pic: false
    list: 
        enable: true
        pic: true
    bind: 
        enable: true
        whitelist: true
        maxNum: 1
        adminBypass: true
        pic: true
    joinAndLeave: 
        pic: false
        joinProxy: true
        leaveProxy: true
        changeServer: true
    img:
        file: "%plugin_folder%/MiSans-Normal.ttf"

database: 
    mode: "sqlite"
    sqlite:
        # 数据库保存路径
        path: "%plugin_folder%/database.db"
    mysql:
        host: localhost
        port: 3306
        database: plumbot
        user: plumbot
        password: plumbot

keys: 
    list: ["在线人数"]
    addBind: ["申请白名单"]
    deleteBind: ["删除白名单"]
    queryBind: ["查询白名单"]

# 调试选项
debug:
    # 是否启用该功能
    enable: false

    # 日志存储文件名
    file: "%plugin_folder%/debug.log"

    # 每隔多长时间保存一次日志文件 (单位: 秒)
    # 设置为 -1 代表关服时保存
    # 设置为 0 代表实时保存 (在有新的日志时就保存)
    save_interval: 0